{% set name = "tributary" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2815a2d2083d019d9ecfe183dbae27e526beacd4156790f761d21a6baa5e9d75

build:
  number: 1
  noarch: python
  skip: true
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aioconsole >=0.4.1
    - aiofiles >=0.4.0
    - aiohttp >=3.5.4
    - aiohttp-sse >=2.1
    - aiohttp-sse-client >=0.2.1
    - aiokafka >=0.6.0
    - aiostream >=0.4.3
    - asyncpg >=0.20.1
    - beautifulsoup4 >=4.9.1
    - boltons >=20.1.0
    - emails >=0.5.15
    - future >=0.17.1
    - gevent >=1.3.7
    - ipydagred3 >=0.1.5
    - ipython >=7.0.1
    - numpy >=1.15.3
    - pandas >=0.19.0
    - python-confluent-kafka >=0.11.6
    - python-graphviz >=0.14.1
    - scipy >=1.2.0
    - six >=1.11.0
    - socketio-client-nexus >=0.7.6
    - sympy >=1.3
    - temporal-cache >=0.0.6
    - tornado >=5.1.1
    - twilio >=6.50.1
    - websockets >=8.0

test:
  imports:
    - tributary

about:
  home: http://github.com/timkpaine/tributary
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python data stream

  description: |
    Python data stream
  dev_url: https://github.com/timkpaine/tributary

extra:
  recipe-maintainers:
    - timkpaine
