{% set name = "tributary" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb628f2fbdbbb581817544886c92e5bdf34aefd57440a1677eee946eea802f70

build:
  number: 1
  skip: true  # [py<37 or (win)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aiohttp >=3.5.4
    - aiofiles >=0.4.0
    - asyncpg >=0.20.1
    - boltons >=20.1.0
    - future >=0.17.1
    - gevent >=1.3.7
    - ipydagred3 >=0.1.5
    - ipython >=7.0.1
    - ipywidgets >=7.5.1
    - networkx >=2.2
    - numpy >=1.15.3
    - pandas >=0.19.0
    - python-confluent-kafka >=0.11.6
    - python-graphviz >=0.14.1
    - scipy >=1.2.0
    - six >=1.11.0
    - socketio-client-nexus >=0.7.6
    - sympy >=1.3
    - temporal-cache >=0.0.6
    - tornado >=5.1.1
    - websockets >=8.0

test:
  imports:
    - tributary

about:
  home: http://github.com/timkpaine/tributary
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python data stream

  description: |
    Python data stream
  dev_url: https://github.com/timkpaine/tributary

extra:
  recipe-maintainers:
    - timkpaine
